### ISSUE TITLE
change perms on this tasks or cluster will break

### ISSUE THREAD

**Issue by aoyawale** [redhat-cop/automate-tower-ha-dr#1]
https://github.com/redhat-cop/automate-tower-ha-dr/blob/0e9efb33db60dd47482bb9eb7db08e25519eef91/tower-dr-standup.yml#L40 to 750

**Comment by aoyawale** [comment]
It was mentioned this causes tower to crash. That 750 are the correct permissions. Need to test.

**Comment by mpetrive-rh** [comment]
Closing based on functionality added in https://github.com/redhat-cop/automate-tower-ha-dr/pull/17
